Description: >
    Sets up an S3 bucket that another account can write files into
    
Parameters:
  AccountID: 
    Description: Source Account ID
    Type: String
    
Resources:
  Bucket:
    Type: "AWS::S3::Bucket"
  
  BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties:
      Bucket: !Ref Bucket
      PolicyDocument:
        Statement: 
        - Action: 
          - "s3:PutObject"
          Effect: "Allow"
          Resource: !Sub "arn:aws:s3:::${Bucket}/*"
          Principal: 
            AWS: !Sub "arn:aws:iam::${AccountID}:root"